### ISSUE TITLE
The given google drive link in the jupyter notebook is down.

### ISSUE THREAD

**Issue by Zimiao1025** [nekitmm/DLPacker#15]
Hi,

I attempted to download the weights from the given google drive link in the jupyter notebook but the link is down. Is there any other way to download them?

**Comment by nekitmm** [comment]
What error are you seeing? You should not need to download the weights manually from google drive anymore! Also, what notebook are you looking at, I think I removed all the google drive links.

**Comment by Zimiao1025** [comment]
![image](https://github.com/nekitmm/DLPacker/assets/91265018/f8376f88-2dcf-4a7f-a2f2-1390e90aae8d)

**Comment by nekitmm** [comment]
Corrected the notebook, you should not need to download the weights manually anymore! Everything should work out of the box.
